# Generated bytecode only. Canonical R sources remain the sole implementation.
arguments <- commandArgs(trailingOnly = TRUE)
if (length(arguments) != 2L) {
    stop("Supply the canonical runtime source directory and output cache path.")
}
sources <- normalizePath(arguments[[1L]], mustWork = TRUE)
output <- arguments[[2L]]
functions <- list()
compilation_environment <- new.env(parent = baseenv())

collect_control_definitions <- function(expression) {
    if (!is.call(expression)) {
        return(invisible(NULL))
    }
    operator <- expression[[1L]]
    if (identical(operator, as.name("<-")) && length(expression) == 3L) {
        definition <- expression[[3L]]
        target <- expression[[2L]]
        name <- if (is.symbol(target)) {
            as.character(target)
        }
        else if (
            is.call(target) && identical(target[[1L]], as.name("$")) &&
            length(target) == 3L && is.symbol(target[[3L]])
        ) {
            as.character(target[[3L]])
        }
        else {
            ""
        }
        if (
            nzchar(name) && is.call(definition) &&
            identical(definition[[1L]], as.name("function"))
        ) {
            value <- eval(definition, envir = compilation_environment)
            compiled <- compiler::cmpfun(value)
            functions[[name]] <<- compiled
        }
        return(invisible(NULL))
    }
    # Do not enter factories/local() or execute source-file startup effects.
    if (identical(operator, as.name("{")) || identical(operator, as.name("if"))) {
        for (index in seq.int(2L, length(expression))) {
            collect_control_definitions(expression[[index]])
        }
    }
    invisible(NULL)
}

for (name in sort(list.files(sources, pattern = "[.]R$"))) {
    expressions <- parse(file = file.path(sources, name), keep.source = FALSE)
    for (expression in expressions) {
        collect_control_definitions(expression)
    }
}
dir.create(dirname(output), recursive = TRUE, showWarnings = FALSE)
saveRDS(list(
    format = 1L,
    r_version = paste(
        R.version$major, strsplit(R.version$minor, ".", fixed = TRUE)[[1L]][[1L]],
        sep = "."
    ),
    optimization = compiler::getCompilerOption("optimize"),
    functions = functions
), output, version = 2L)
cat("Generated shared runtime cache:", length(functions), "closures,",
    file.info(output)$size, "bytes\n")
